gravitee-repository-elasticsearch/src/main/resources/freemarker/analyticsRequest.ftl
gravitee-repository-elasticsearch/src/main/resources/freemarker/dateHistogram.ftl
gravitee-repository-elasticsearch/src/main/resources/freemarker/healthcheck/avg-date-histogram.ftl

Hello,
I propose you this PR I've tested with our OPS.
The details are in the issue gravitee-io/issues#1545
Nicolas

fix(cache-missed): remove extended_bounds so that the query always hits the cache

---

gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/configuration/RepositoryConfiguration.java
gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/spring/ElasticsearchRepositoryConfiguration.java
gravitee-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/configuration/ElasticsearchRepositoryConfigurationTest.java
gravitee-repository-elasticsearch/src/test/resources/configuration/gravitee.yml

Configurable timeout to handle long running elasticsearch queries in case of a large time window or many statistics data
fix gravitee-io/issues#1920

Configurable timeout for the analytics repository client

---

gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/ElasticsearchReporter.java

gravitee-reporter-elasticsearch shoud ignore Reportable-s it can not handle.

issue/#2320 reporter should only handle objects it canHandle()

---

gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-log.ftl

This closes gravitee-io/issues#4685

fix: Template mapping of log is incorrect with ES 7.x

---

gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java

Closes gravitee-io/issues#4919

fix(elasticsearch): Connector must retry to connect to Elasticsearch when receiving bad info

---

gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/ElasticsearchReporter.java
gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/name/AbstractPerTypeIndexNameGenerator.java
gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/name/PerTypeAndDateIndexNameGenerator.java
gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/spring/context/Elastic6xBeanRegistrer.java
gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/spring/context/Elastic7xBeanRegistrer.java
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-health.ftl
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-log.ftl
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-monitor.ftl
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-health.ftl
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-monitor.ftl
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/indexer/name/PerTypeAndDateIndexNameGeneratorTest.java
gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/indexer/name/PerTypeIndexNameGeneratorTest.java

https://github.com/gravitee-io/issues/issues/6507
ILM managed indexes names aren't suffixed by the date.
It's properly handled in repository side for ES>=6, but not in reporter side.
So, when user uses gravitee.analytics.elasticsearch.index_mode=ilm parameter in rest API,
It doesn't read on the same indexes gateway is writing on.
This modification implements ILM managed index on reporter side,
That can be enabled with gravitee.reporters.elasticsearch.index_mode=ilm parameter.
I didn't put much effort on code refactoring here, cause some of those components will be refactored during openSearch support implementation (see https://github.com/gravitee-io/issues/issues/6423)

fix: implement ILM managed indexes in reporter

---

gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/PipelineConfiguration.java
gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/es7/ES7IndexPreparer.java
gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/config/PipelineConfigurationTest.java

https://github.com/gravitee-io/issues/issues/6683
Always enable geoip and user_agent plugins by default
Those plugins where enabled by default for ES>=7, and we don't permit to disable them.
That causes problems for users running Gravitee against ES>=7 without GeoIp enabled on server side.
Now, they are always enabled by default, but user can disable them using the reporters.elasticsearch.pipeline.plugins.ingest configuration.
Behavior is the same for all ES versions.

feat: always enable geoip and user_agent plugins by default

---

gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/health.ftl
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/health.ftl
gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/index/health.ftl

Following the refactor of the HTTP Headers API, a FreeMarker template error was reported in the logs
and the health check was not indexed on endpoint responses containing custom HTTP headers.
see https://github.com/gravitee-io/issues/issues/6964

fix(health): parse headers according to new data model

---

pom.xml
src/main/java/io/gravitee/elasticsearch/client/Client.java
src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
src/test/java/io/gravitee/elasticsearch/client/HttpClientTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/7110
add method to manage alias
---
- use it directly by updating your project with version: `3.8.5-7110-fix-ILM-support-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/3.8.5-7110-fix-ILM-support-SNAPSHOT/gravitee-common-elasticsearch-3.8.5-7110-fix-ILM-support-SNAPSHOT.zip)

add method to manage alias

---

pom.xml
src/test/java/io/gravitee/elasticsearch/client/HttpClientTest.java
src/test/java/io/gravitee/elasticsearch/index/ILMIndexNameGeneratorTest.java
src/test/java/io/gravitee/elasticsearch/templating/freemarker/FreeMarkerComponentTest.java
src/test/java/io/gravitee/elasticsearch/utils/DateUtilsTest.java

Migrate tests to JUnit 5
---
- use it directly by updating your project with version: `4.1.0-move-to-junit5-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/4.1.0-move-to-junit5-SNAPSHOT/gravitee-common-elasticsearch-4.1.0-move-to-junit5-SNAPSHOT.zip)

test: move to JUnit 5

---

pom.xml
src/main/resources/freemarker/es7x/index/message-metrics-v4.ftl

rename errorsCount to errorCount in message metrics
---
- use it directly by updating your project with version: `4.1.0-fix-metrics-name-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/4.1.0-fix-metrics-name-SNAPSHOT/gravitee-common-elasticsearch-4.1.0-fix-metrics-name-SNAPSHOT.zip)

fix: rename metrics for message

---

pom.xml
src/main/resources/freemarker/es7x/index/v4-message-log.ftl
src/main/resources/freemarker/es7x/index/v4-message-metrics.ftl
src/main/resources/freemarker/es7x/mapping/index-template-v4-message-log.ftl
src/main/resources/freemarker/es7x/mapping/index-template-v4-message-metrics.ftl

Description
Adding error status on message metrics.
---
- use it directly by updating your project with version: `4.1.0-apim-490-add-error-metric-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/4.1.0-apim-490-add-error-metric-SNAPSHOT/gravitee-common-elasticsearch-4.1.0-apim-490-add-error-metric-SNAPSHOT.zip)

Apim 490 add error metric

---

README.adoc
pom.xml
src/main/java/io/gravitee/elasticsearch/utils/Type.java
src/main/java/io/gravitee/elasticsearch/version/Version.java
src/main/resources/freemarker/es8x/alias/alias.ftl
src/main/resources/freemarker/es8x/index/health.ftl
src/main/resources/freemarker/es8x/index/log.ftl
src/main/resources/freemarker/es8x/index/monitor.ftl
src/main/resources/freemarker/es8x/index/request.ftl
src/main/resources/freemarker/es8x/index/v4-log.ftl
src/main/resources/freemarker/es8x/index/v4-message-log.ftl
src/main/resources/freemarker/es8x/index/v4-message-metrics.ftl
src/main/resources/freemarker/es8x/index/v4-metrics.ftl
src/main/resources/freemarker/es8x/mapping/index-template-health.ftl
src/main/resources/freemarker/es8x/mapping/index-template-log.ftl
src/main/resources/freemarker/es8x/mapping/index-template-monitor.ftl
src/main/resources/freemarker/es8x/mapping/index-template-request.ftl
src/main/resources/freemarker/es8x/mapping/index-template-v4-log.ftl
src/main/resources/freemarker/es8x/mapping/index-template-v4-message-log.ftl
src/main/resources/freemarker/es8x/mapping/index-template-v4-message-metrics.ftl
src/main/resources/freemarker/es8x/mapping/index-template-v4-metrics.ftl
src/test/java/io/gravitee/elasticsearch/client/HttpClientTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-427
Add ES 8 support
---
- use it directly by updating your project with version: `4.1.0-es8-support-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/4.1.0-es8-support-SNAPSHOT/gravitee-common-elasticsearch-4.1.0-es8-support-SNAPSHOT.zip)

Add ES 8 support

---

pom.xml
src/main/java/io/gravitee/elasticsearch/utils/DateUtils.java
src/test/java/io/gravitee/elasticsearch/utils/DateUtilsTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-844
Use wildcards when computing elastic query indices. The reason behind that is to be able to compute analytics for date range greater than 90 days. Today we concat the daily indices, that why we can reich the request size limit
---
- use it directly by updating your project with version: `4.2.0-apim-844-use-wildcards-on-indices-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/4.2.0-apim-844-use-wildcards-on-indices-SNAPSHOT/gravitee-common-elasticsearch- …

feat: use wildcards when computing elastic query indices

---

src/main/java/io/gravitee/elasticsearch/templating/freemarker/FreeMarkerComponent.java

FreemarkerCompoennt is marked for removal as dependant modules should use the one made available in gravitee-common since version 3.3.0.
---
- use it directly by updating your project with version: `5.0.1-fix-deprecate-freemarker-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/5.0.1-fix-deprecate-freemarker-SNAPSHOT/gravitee-common-elasticsearch-5.0.1-fix-deprecate-freemarker-SNAPSHOT.zip)

fix: deprecate freemarker component

---

src/main/resources/freemarker/es7x/index/health.ftl
src/main/resources/freemarker/es7x/index/log.ftl
src/main/resources/freemarker/es7x/index/request.ftl
src/main/resources/freemarker/es7x/index/v4-log.ftl
src/main/resources/freemarker/es7x/index/v4-metrics.ftl
src/main/resources/freemarker/es8x/index/health.ftl
src/main/resources/freemarker/es8x/index/log.ftl
src/main/resources/freemarker/es8x/index/request.ftl
src/main/resources/freemarker/es8x/index/v4-log.ftl
src/main/resources/freemarker/es8x/index/v4-metrics.ftl

**Issue**
https://gravitee.atlassian.net/browse/APIM-3180
this fix this error
for es8:
`{"type":"json_parse_exception","reason":"Unrecognized character escape '%' (code 37)...`
for es7:
`ERROR i.g.e.client.http.HttpClient - An error occurs while indexing data into ES: indice[gravitee-log-2023.11.02] error[failed to parse]` if you can you API with escaped % like : `http://localhost:8082/echo?abc=\%`
---
- use it directly by updating your project with version: `4.2.1-4-x-APIM-3180-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/el …

fix: add j_string to escape endpoint URL

---

src/main/java/io/gravitee/elasticsearch/client/Client.java
src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
src/test/java/io/gravitee/elasticsearch/client/HttpClientTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-3014
Add method to put index template
---
- use it directly by updating your project with version: `5.1.0-apim3014-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/5.1.0-apim3014-SNAPSHOT/gravitee-common-elasticsearch-5.1.0-apim3014-SNAPSHOT.zip)

feat: add method to put index template

---

src/main/java/io/gravitee/elasticsearch/client/Client.java
src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
src/test/java/io/gravitee/elasticsearch/client/HttpClientTest.java

**Issue**
https://github.com/gravitee-io/issues/issues/5102
Get index field types. It will allow us to create the good query when we update a mapping template
---
- use it directly by updating your project with version: `6.1.0-apim-5102-get-field-types-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/6.1.0-apim-5102-get-field-types-SNAPSHOT/gravitee-common-elasticsearch-6.1.0-apim-5102-get-field-types-SNAPSHOT.zip)

feat: get index field types

---

pom.xml
src/main/java/io/gravitee/elasticsearch/client/Client.java
src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
src/main/java/io/gravitee/elasticsearch/exception/OpensearchException.java
src/test/java/io/gravitee/elasticsearch/client/HttpClientOpensearchTest.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-7236
Create or Update policy to be able to configure index state management .
See for more details https://opensearch.org/docs/latest/im-plugin/ism/api/
---
- use it directly by updating your project with version: `5.1.1-apim-7236-add-policy-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/5.1.1-apim-7236-add-policy-SNAPSHOT/gravitee-common-elasticsearch-5.1.1-apim-7236-add-policy-SNAPSHOT.zip)

Create or Update policy to be able to configure index state management 

---

pom.xml
src/main/java/io/gravitee/elasticsearch/client/Client.java
src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java

**Issue**
https://gravitee.atlassian.net/browse/ARCHI-435
Just adding a new method taking simple buffer for bulk fonction.
---
- use it directly by updating your project with version: `6.2.0-archi-435-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/6.2.0-archi-435-SNAPSHOT/gravitee-common-elasticsearch-6.2.0-archi-435-SNAPSHOT.zip)

feat: add new bulk method with simple buffer

---

src/main/java/io/gravitee/elasticsearch/utils/Type.java

**Issue**
https://gravitee.atlassian.net/browse/APIM-10024?atlOrigin=eyJpIjoiY2UxZWQwNTFhZDM1NDAxOTg1ZmZlYTQ2OTc1Y2NiMmYiLCJwIjoiaiJ9
Add new EVENT_METRICS type. We need it to have the right index name into ES
---
- use it directly by updating your project with version: `6.3.0-APIM-10024-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/6.3.0-APIM-10024-SNAPSHOT/gravitee-common-elasticsearch-6.3.0-APIM-10024-SNAPSHOT.zip)

feat: add new EVENT_METRICS type
