- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/ElasticsearchReporter.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
Closes gravitee-io/issues#1179
> Disable ES reporter

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/Client.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/ElasticsearchReporter.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/ES2IndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/ES5IndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/ES6IndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/geoip.ftl
Closes gravitee-io/issues#1188
> fix(elasticsearch): Default value for country code if none found

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/ElasticsearchReporter.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/BulkIndexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/AbstractIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/PerTypeIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/es2/ES2MultiTypeIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/es2/ES2PerTypeIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/es5/ES5MultiTypeIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/es5/ES5PerTypeIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/es6/ES6IndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/spring/context/Elastic2xBeanRegistrer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/spring/context/Elastic5xBeanRegistrer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/spring/context/Elastic6xBeanRegistrer.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-monitor.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-monitor.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/configuration/RepositoryConfiguration.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/spring/ElasticsearchRepositoryConfiguration.java
Closes gravitee-io/issues#1210
> feat(elasticsearch): Index per type support for both ES 2.x and ES 5.x

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/log.ftl
Closes gravitee-io/issues#1270
> fix(elasticsearch): Skip headers without value

- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/AverageDateHistogramCommand.java
This closes gravitee-io/issues#1083
> fix: take care of dates on HC zoom

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/health.ftl
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/ElasticsearchReporterTest.java
- gravitee-repository-elasticsearch/pom.xml
- gravitee-repository-elasticsearch/src/main/resources/freemarker/healthcheck/logs.ftl
- gravitee-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/AbstractElasticsearchRepositoryTest.java
- pom.xml
This closes gravitee-io/issues#1240
> feat: allows to display HC status transitions

- gravitee-reporter-elasticsearch/pom.xml
- gravitee-repository-elasticsearch/pom.xml
- pom.xml
> chore: use dependency-management for the release

- gravitee-common-elasticsearch/pom.xml
- gravitee-reporter-elasticsearch/pom.xml
- gravitee-repository-elasticsearch/pom.xml
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/log/ElasticLogRepository.java
- gravitee-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/AbstractElasticsearchRepositoryTest.java
- gravitee-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/ElasticsearchLogRepositoryTest.java
- pom.xml
closes gravitee-io/issues#1412
> feat(log): add log timestamp to select elasticsearch indices

- gravitee-common-elasticsearch/src/test/java/io/gravitee/elasticsearch/node/DummyNode.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexer.java
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/node/DummyNode.java
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/spring/ElasticsearchReporterConfigurationTest.java
- pom.xml
Closes gravitee-io/issues#1409
> feat(node): Moving the Node from common module to Node API module

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClientConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/spring/ElasticsearchReporterConfiguration.java
Closes gravitee-io/issues#1508
> fix(elasticsearch): Add options to configure the request timeout

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/log/LogBuilder.java
- pom.xml
Closes gravitee-io/issues#1536
> feat(analytics): Add Host HTTP header into analytics

- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/LogBuilder.java
This closes gravitee-io/issues#1583
> fix: Sometimes errors occurs while reporting HC

- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/AbstractElasticsearchQueryCommand.java
This closes gravitee-io/issues#1766
> feat: Better handling of character escaping on analytics

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/request.ftl
Closes gravitee-io/issues#1021
> fix(elasticsearch): Escape request message's content for java string

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/PipelineConfiguration.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/user_agent.ftl
- pom.xml
This closes gravitee-io/issues#1951
> feat: Add an option to get hits by user agent in analytics dashboard

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
- pom.xml
> chore: Java 11 support

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexer.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/log.ftl
Closes gravitee-io/issues#1993
> feat(log): Add API ID and timestamp to logs

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
> fix(reporter): improve the default configuration

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/request.ftl
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/log/LogBuilder.java
- pom.xml
This closes gravitee-io/issues#1948
> feat: Audit on API user from JWT

- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/configuration/RepositoryConfiguration.java
> fix(timeout): same client timeout variable for repository & reporter

- gravitee-repository-elasticsearch/src/main/resources/freemarker/log/log.ftl
- pom.xml
This closes gravitee-io/issues#2003
> feat: Allows to sort the logs by date, path, status

- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/AbstractElasticsearchQueryCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/DateHistogramQueryCommand.java
- gravitee-repository-elasticsearch/src/main/resources/freemarker/dateHistogram.ftl
> fix: improve-date-histo-request

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/templating/freemarker/FreeMarkerComponent.java
- gravitee-common-elasticsearch/src/test/java/io/gravitee/elasticsearch/templating/freemarker/FreeMarkerComponentTest.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/AbstractIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/spring/ElasticsearchReporterConfiguration.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/spring/ElasticsearchRepositoryConfiguration.java
This closes gravitee-io/issues#2084
> feat: Allows to extend ES index mapping

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/templating/freemarker/FreeMarkerComponent.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-log.ftl
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/log/ElasticLogRepository.java
- gravitee-repository-elasticsearch/src/main/resources/freemarker/index-template-es-5x.ftl
- gravitee-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/ElasticsearchLogRepositoryTest.java
- pom.xml
This closes gravitee-io/issues#2053
> feat: Allows to search in logs payloads

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-monitor.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
> fix(template): es5 templates errors if index_per_type=true

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/Client.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/templating/freemarker/FreeMarkerComponent.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/ElasticsearchReporter.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/BulkIndexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/Indexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/es2/ES2BulkIndexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/es5/ES5BulkIndexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/es6/ES6BulkIndexer.java
- pom.xml
Closes gravitee-io/issues#2247
> reporter(elasticsearch): Improve memory usage

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/request.ftl
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/log/LogBuilder.java
- pom.xml
This closes gravitee-io/issues#1997
> feat: Multi analytics dashboards

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/BulkIndexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/DocumentBulkProcessor.java
- pom.xml
Closes gravitee-io/issues#2305
> fix(elasticsearch): Set vertx dependencies as provided

- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/LogsCommand.java
- gravitee-repository-elasticsearch/src/main/resources/freemarker/healthcheck/avg-date-histogram.ftl
- gravitee-repository-elasticsearch/src/main/resources/freemarker/healthcheck/logs.ftl
- pom.xml
closes gravitee-io/issues#2378
> feat(healthcheck): adding a time filter in the healthcheck screen

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/PipelineConfiguration.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/gravitee.ftl
> feat: Ingest plugin to store the application/API names

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/index/AbstractIndexNameGenerator.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/index/IndexNameGenerator.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/AbstractElasticsearchQueryCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/ElasticsearchHealthCheckRepository.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/AbstractElasticsearchQueryCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/AverageAvailabilityCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/AverageDateHistogramCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/AverageResponseTimeCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/LogsCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/log/ElasticLogRepository.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/monitoring/ElasticsearchMonitoringRepository.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/utils/ClusterUtils.java
- gravitee-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/utils/ClusterUtilsTest.java
> fix(ccs): use tenant prefix on all repository requests

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
> fix: Extended request mapping is not taken into account

- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/DateHistogramQueryCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/AverageDateHistogramCommand.java
- gravitee-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/analytics/query/DateHistogramQueryCommandTest.java
> fix: Optimization of date histogram queries is not working on some cases

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/request.ftl
> feat: Add a sparkline graph on subscriptions list

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
> fix: Error when updating the request's index template

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
Closes gravitee-io/issues#2735
> feat(request): The message in case of error is now searchable

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/Client.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/model/CountResponse.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/model/Response.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/model/SearchResponse.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/geoip.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/user_agent.ftl
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/AbstractElasticsearchQueryCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/CountQueryCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/StatsQueryCommand.java
- gravitee-repository-elasticsearch/src/main/resources/freemarker/count.ftl
- gravitee-repository-elasticsearch/src/main/resources/freemarker/groupBy.ftl
Closes gravitee-io/issues#2595
> feat: Dynamic global dashboards of analytics

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
- gravitee-repository-elasticsearch/src/main/resources/freemarker/index-template-es-5x.ftl
> fix(template): index remote address

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
Closes gravitee-io/issues#2952
> fix(elasticsearch): Update field type for body payload

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
> fix(httpClient): allow path in endpoints

- gravitee-repository-elasticsearch/src/main/resources/freemarker/groupBy.ftl
> fix(groupBy): aggregation by response-time doesnt work

- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/analytics/query/GroupByQueryCommand.java
- gravitee-repository-elasticsearch/src/main/resources/freemarker/groupBy.ftl
Closes gravitee-io/issues#3041
> fix: analytic widgets with latency displayed hits instead of latency

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-monitor.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-monitor.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-monitor.ftl
Closes gravitee-io/issues#2692
> fix: cannot index a cpu loadaverage as long

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/BulkIndexer.java
Closes gravitee-io/issues#3630
> fix(reporter): Do not stop if bulk indexer encounters error

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
> fix: Change the default values for the number of shards/replicas

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
> feat: Change the default values for the number of shards/replicas

- gravitee-repository-elasticsearch/src/main/resources/freemarker/healthcheck/avg-date-histogram.ftl
Closes gravitee-io/issues#3864
> fix(healthcheck): disable_coord is deprecated since ES 6.x

- gravitee-reporter-elasticsearch/pom.xml
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexer.java
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexerTest.java
- pom.xml
> fix(metrics): handle invalid remote address values

- gravitee-reporter-elasticsearch/pom.xml
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexer.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/AbstractIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-monitor.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/indexer/AbstractIndexerTest.java
- gravitee-repository-elasticsearch/src/main/resources/freemarker/healthcheck/avg-date-histogram.ftl
- pom.xml
> chore: Merge 1.30.11

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClientConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/spring/ElasticsearchReporterConfiguration.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/configuration/RepositoryConfiguration.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/spring/ElasticsearchRepositoryConfiguration.java
Closes gravitee-io/issues#3354
> feat(http): Add support for HTTP proxy

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/request.ftl
> feat: Support zone in order to group analytics

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/request.ftl
> fix(reporter): escape user-agent value

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/index/request.ftl
Closes gravitee-io/issues#4139
> fix(reporter): Do not apply string escaping on empty or missing value

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
This would avoid bad index mapping when the first element to index contains bad values
Closes gravitee-io/issues#4138
> fix(mapping): Define properly the user_agent mapping 

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
> fix: Index proxy-latency

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/PipelineConfiguration.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/user_agent.ftl
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/config/PipelineConfigurationTest.java
> feat: Allows to configure custom regexes on the user agent processor

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/AbstractIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-monitor.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
> fix(reporters): allow to configure property name of ILM

- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/AverageAvailabilityCommand.java
- gravitee-repository-elasticsearch/src/main/java/io/gravitee/repository/elasticsearch/healthcheck/query/AverageResponseTimeCommand.java
> fix: Do not display a gauge when no health check value

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
> fix: invalid default value for ILM lifecycle property name

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/config/ElasticsearchClient.java
> fix: Load balancing is not well done on runtime

- gravitee-common-elasticsearch/src/main/java/io/gravitee/elasticsearch/client/http/HttpClient.java
Closes gravitee-io/issues#4350
> fix(elasticsearch): Do not run health-check if the reporter is disabled

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
> fix: Invalid mapping for index request for ES6

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/ReporterConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/AbstractIndexPreparer.java
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-monitor.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-health.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-monitor.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
> feat: add settings to search slow log

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/log.ftl
> fix(logs): fix log.ftl for the logging proxy only mode

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/indexer/DocumentBulkProcessor.java
> fix(bulk): continue events streaming after unexpected errors

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
Closes gravitee-io/issues#4686
> chore(): Prepare next version

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
Closes gravitee-io/issues#4721
> Merge 1.30.27

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es2x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
> fix(ES reporter): do not index headers to avoid too many field error

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/config/PipelineConfiguration.java
- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/mapping/es7/ES7IndexPreparer.java
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/config/PipelineConfigurationTest.java
Fixes https://github.com/gravitee-io/issues/issues/4744
> feat: auto-enable geoip and user_agent when elasticsearch > 7.x

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/index/request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/mapping/index-template-request.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/request.ftl
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/ElasticsearchReporterTest.java
- pom.xml
Closes gravitee-io/issues#4769
> feat(assign-metrics): use custom metrics in reporter

- pom.xml
Closes gravitee-io/issues#5582
> chore: Update freemarker version to 2.3.30 for reporter elastic

- gravitee-common-elasticsearch/pom.xml
- gravitee-reporter-elasticsearch/pom.xml
- gravitee-repository-elasticsearch/pom.xml
- pom.xml
Closes gravitee-io/issues#5580
> chore: Upgrade to Vert.x 4.x and move to Gravitee BOM

- gravitee-reporter-elasticsearch/src/main/java/io/gravitee/reporter/elasticsearch/spring/context/Elastic5xBeanRegistrer.java
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/spring/IndexNameGeneratorRegistrationTest.java
see https://github.com/gravitee-io/issues/issues/6630
> fix: generate elastic 5 index names with date

- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es5x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es6x/index/log.ftl
- gravitee-reporter-elasticsearch/src/main/resources/freemarker/es7x/index/log.ftl
- gravitee-reporter-elasticsearch/src/test/java/io/gravitee/reporter/elasticsearch/ElasticsearchReporterTest.java
- pom.xml
Closes gravitee-io/issues#6772
> feat(headers): Internal rework and introduce HTTP Headers API

- gravitee-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/ElasticsearchLogRepositoryTest.java
> test: fix ElasticsearchLogRepositoryTest

- gravitee-repository-elasticsearch/src/test/java/io/gravitee/repository/elasticsearch/ElasticsearchLogRepositoryTest.java
introduced with gravitee-io/issues#6913
> test(repository): fix flaky test

- pom.xml
- src/main/java/io/gravitee/elasticsearch/utils/Type.java
- src/main/resources/freemarker/es7x/index/log-v4.ftl
- src/main/resources/freemarker/es7x/index/message-log-v4.ftl
- src/main/resources/freemarker/es7x/index/message-metrics-v4.ftl
- src/main/resources/freemarker/es7x/index/metrics-v4.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-log-v4.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-message-log-v4.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-message-metrics-v4.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-metrics-v4.ftl
**Issue**
https://gravitee.atlassian.net/browse/APIM-490
---
- use it directly by updating your project with version: `4.1.0-support-v4-logging-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/4.1.0-support-v4-logging-SNAPSHOT/gravitee-common-elasticsearch-4.1.0-support-v4-logging-SNAPSHOT.zip)
> APIM-490 feat: define template for log-v4 and request-v4

- src/main/resources/freemarker/es7x/index/v4-metrics.ftl
**Issue**
https://gravitee.atlassian.net/browse/APIM-490
Fix test on getPathInfo that was still using old method name.
> fix: fix v4 metrics index

- src/main/resources/freemarker/es6x/mapping/index-template-log.ftl
- src/main/resources/freemarker/es7x/mapping/index-template-log.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-log.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-log.ftl
- src/main/resources/freemarker/es8x/mapping/index-template-v4-message-log.ftl
see https://gravitee.atlassian.net/browse/APIM-851 
see gravitee-io/issues#8470
---
- use it directly by updating your project with version: `4.1.0-fix-log-body-template-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/4.1.0-fix-log-body-template-SNAPSHOT/gravitee-common-elasticsearch-4.1.0-fix-log-body-template-SNAPSHOT.zip)
> fix: use custom body analyzer

- README.adoc
- pom.xml
- src/main/java/io/gravitee/elasticsearch/index/AbstractIndexNameGenerator.java
- src/main/java/io/gravitee/elasticsearch/index/ILMIndexNameGenerator.java
- src/main/java/io/gravitee/elasticsearch/index/IndexNameGenerator.java
- src/main/java/io/gravitee/elasticsearch/index/PerTypeIndexNameGenerator.java
- src/main/java/io/gravitee/elasticsearch/utils/IndexNameUtils.java
- src/test/java/io/gravitee/elasticsearch/index/MultiTypeIndexNameGeneratorTest.java
- src/test/java/io/gravitee/elasticsearch/index/PerTypeIndexNameGeneratorTest.java
- src/test/java/io/gravitee/elasticsearch/utils/IndexNameUtilsTest.java
**Issue**
https://gravitee.atlassian.net/browse/CJ-1757
Allow placeholder in elasticsearch index name
---
- use it directly by updating your project with version: `6.0.0-placeholder-index-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/elasticsearch/gravitee-common-elasticsearch/6.0.0-placeholder-index-SNAPSHOT/gravitee-common-elasticsearch-6.0.0-placeholder-index-SNAPSHOT.zip)
> feat: allow index name with placeholders for orgId or and/or envId

- src/main/java/io/gravitee/elasticsearch/utils/Type.java
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
A small description of what you did in that PR.
> feat: add new EVENT_METRICS type

- pom.xml
> Clean dependencies scope
